# Workflow intended to properly build the GitHub Pages Site. Using PNPM 

name: Deployment Docs - PNPM 

on:
  # Trigger deployment on every push to main branch.
  push:
    branches: [main]
  # Trigger deployment manually.
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest 
    
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all commits to get last updated time or other git log info 
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Setup PNPM 
        run: npm install -g pnpm@v7.0.0
      # Cache node_modules 
      - name: Cache Dependencies 
        uses: actions/cache@v2
        id: pnpm-cache 
        with:
          path: |
            **/node_modules 
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install Dependencies 
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install 
      - name: Build VuePress Site 
        run: pnpm run docs:build 
      - name: Deploy to GitHub Pages 
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages 
          build_dir: docs/.vuepress/dist 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
