# Workflow to lint Markdown provided 

name: Lint 

on:
  push:
    branches: [main]
  workflow_dispatch:
    
jobs:
  lint:
    runs-on: ubuntu-latest 
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Cache Dependencies 
        uses: actions/cache@v2
        id: yarn-cache 
        with: 
          path: |
            **/node_modules 
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies 
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile 
      - name: Run Linting 
        run: yarn run lint 
